### ISSUE TITLE
. P1 *** Actions*** N peut ajouter un commentaires sous les templates d'actions

### ISSUE THREAD

**Issue by sanh-sandra** [SocialGouv/pass-emploi-web#25]
- [x] N a la possibilité  d'ajouter un commentaire sous une actions prédéfinies 
- [x] N a un nombre de caractères contraint

lien temporaire pour test : https://pa-front-staging-pr30.osc-fr1.scalingo.io/

@sanh-sandra manque la flèche de retour dans la modale "ajouter un commentaire"

(peut-être pas indiqué dans les maquettes ? on en avait parlé avec augustin et sarah)

**Comment by isabelle-cerrutti** [comment]
Pas de nombre de caractère contraint ?

**Comment by isabelle-cerrutti** [comment]
On ne peut pas modifier un commentaire
